import { basename, extname } from "node:path";

const LANGUAGE_MAP: Record<string, string> = {
	".ts": "typescript",
	".tsx": "typescriptreact",
	".js": "javascript",
	".jsx": "javascriptreact",
	".mjs": "javascript",
	".cjs": "javascript",
	".mts": "typescript",
	".cts": "typescript",
	".vue": "vue",
	".svelte": "svelte",
	".astro": "astro",
	".rs": "rust",
	".go": "go",
	".mod": "go",
	".sum": "go",
	".py": "python",
	".pyi": "python",
	".html": "html",
	".htm": "html",
	".css": "css",
	".scss": "scss",
	".sass": "sass",
	".less": "less",
	".json": "json",
	".jsonc": "jsonc",
	".md": "markdown",
	".markdown": "markdown",
	".java": "java",
	".kt": "kotlin",
	".kts": "kotlin",
	".scala": "scala",
	".sbt": "scala",
	".sc": "scala",
	".hs": "haskell",
	".lhs": "haskell",
	".ml": "ocaml",
	".mli": "ocaml",
	".mll": "ocaml",
	".mly": "ocaml",
	".ex": "elixir",
	".exs": "elixir",
	".heex": "elixir",
	".eex": "elixir",
	".erl": "erlang",
	".hrl": "erlang",
	".gleam": "gleam",
	".rb": "ruby",
	".rake": "ruby",
	".gemspec": "ruby",
	".erb": "ruby",
	".sh": "shell",
	".bash": "shell",
	".zsh": "shell",
	".lua": "lua",
	".php": "php",
	".phtml": "php",
	".cs": "csharp",
	".csx": "csharp",
	".yaml": "yaml",
	".yml": "yaml",
	".toml": "toml",
	".tf": "terraform",
	".tfvars": "terraform",
	".nix": "nix",
	".odin": "odin",
	".dart": "dart",
	".tex": "tex",
	".bib": "tex",
	".sty": "tex",
	".cls": "tex",
	".graphql": "graphql",
	".gql": "graphql",
	".prisma": "prisma",
	".vim": "vim",
	".vimrc": "vim",
	".swift": "swift",
	".tpl": "helm",
};

export function detectLanguageIdFromPath(filePath: string): string | undefined {
	const fileBaseName = basename(filePath).toLowerCase();
	if (fileBaseName === "dockerfile" || fileBaseName.startsWith("dockerfile.")) {
		return "dockerfile";
	}
	if (fileBaseName === ".vimrc") {
		return "vim";
	}

	return LANGUAGE_MAP[extname(filePath).toLowerCase()];
}
